curl -i -X POST -H "Content-Type:application/json" -d "{  \"firstName\" : \"Alex\",  \"lastName\" :  \"K\",\"sity_id\" : 1  }" http://localhost:8080/people
curl -i -X POST -H "Content-Type:application/json" -d "{  \"firstName\" : \"Bulat\",  \"lastName\" : \"V\",\"sity_id\" : 1 }" http://localhost:8080/people
curl -i -X POST -H "Content-Type:application/json" -d "{  \"firstName\" : \"Lena\",  \"lastName\" :  \"S\",\"sity_id\" : 2 }" http://localhost:8080/people
curl -i -X POST -H "Content-Type:application/json" -d "{  \"firstName\" : \"Anna\",  \"lastName\" :  \"P\",\"sity_id\" : 2 }" http://localhost:8080/people
curl -i -X POST -H "Content-Type:application/json" -d "{  \"firstName\" : \"Artem\",  \"lastName\" :  \"M\",\"sity_id\" : 2 }" http://localhost:8080/people
